# -*- coding: utf-8 -*-
import json

# (id, category, tr, en, de, kcal_per_100g_or_100ml)
BASE_FOODS = [
# --- Meyveler / Fruits / Obst ---
("fruit","Elma","Apple","Apfel",52),
("fruit","Armut","Pear","Birne",57),
("fruit","Muz","Banana","Banane",89),
("fruit","Portakal","Orange","Orange",47),
("fruit","Mandalina","Tangerine","Mandarine",53),
("fruit","Greyfurt","Grapefruit","Grapefruit",42),
("fruit","Çilek","Strawberry","Erdbeere",32),
("fruit","Kiraz","Cherry","Kirsche",63),
("fruit","Vişne","Sour cherry","Sauerkirsche",50),
("fruit","Şeftali","Peach","Pfirsich",39),
("fruit","Kayısı","Apricot","Aprikose",48),
("fruit","Erik","Plum","Pflaume",46),
("fruit","Taze incir","Fresh fig","Frische Feige",74),
("fruit","Üzüm","Grapes","Weintrauben",69),
("fruit","Karpuz","Watermelon","Wassermelone",30),
("fruit","Kavun","Melon","Honigmelone",34),
("fruit","Ananas","Pineapple","Ananas",50),
("fruit","Mango","Mango","Mango",60),
("fruit","Kivi","Kiwi","Kiwi",61),
("fruit","Nar","Pomegranate","Granatapfel",83),
("fruit","Avokado","Avocado","Avocado",160),
("fruit","Hurma","Date","Dattel",277),
("fruit","Yaban mersini","Blueberry","Heidelbeere",57),
("fruit","Ahududu","Raspberry","Himbeere",52),
("fruit","Böğürtlen","Blackberry","Brombeere",43),
# --- Sebzeler / Vegetables / Gemüse ---
("veg","Domates","Tomato","Tomate",18),
("veg","Salatalık","Cucumber","Gurke",15),
("veg","Biber (dolmalık)","Bell pepper","Paprika",31),
("veg","Havuç","Carrot","Karotte",41),
("veg","Patates (haşlanmış)","Potato (boiled)","Kartoffel (gekocht)",87),
("veg","Kabak","Zucchini","Zucchini",17),
("veg","Patlıcan","Eggplant","Aubergine",25),
("veg","Ispanak","Spinach","Spinat",23),
("veg","Brokoli","Broccoli","Brokkoli",34),
("veg","Karnabahar","Cauliflower","Blumenkohl",25),
("veg","Mısır","Corn","Mais",96),
("veg","Mantar","Mushroom","Pilz",22),
("veg","Soğan","Onion","Zwiebel",40),
("veg","Sarımsak","Garlic","Knoblauch",149),
("veg","Bezelye","Peas","Erbsen",81),
("veg","Pırasa","Leek","Lauch",61),
("veg","Lahana","Cabbage","Kohl",25),
("veg","Kırmızı lahana","Red cabbage","Rotkohl",31),
("veg","Kereviz","Celery","Sellerie",16),
("veg","Turp","Radish","Radieschen",16),
("veg","Enginar","Artichoke","Artischocke",47),
("veg","Kuşkonmaz","Asparagus","Spargel",20),
("veg","Şalgam (sebze)","Turnip","Steckrübe",28),
("veg","Bal kabağı","Pumpkin","Kürbis",26),
("veg","Semizotu","Purslane","Portulak",20),
# --- Ekmek / Tahıllar / Bread & Grains / Brot & Getreide ---
("grain","Beyaz ekmek","White bread","Weißbrot",265),
("grain","Tam buğday ekmek","Whole wheat bread","Vollkornbrot",247),
("grain","Çavdar ekmeği","Rye bread","Roggenbrot",259),
("grain","Baget","Baguette","Baguette",274),
("grain","Simit","Simit (sesame bread ring)","Simit (Sesamring)",310),
("grain","Poğaça","Poğaça (savory pastry)","Poğaça (herzhaftes Gebäck)",380),
("grain","Pirinç (pişmiş)","Rice (cooked)","Reis (gekocht)",130),
("grain","Bulgur (pişmiş)","Bulgur (cooked)","Bulgur (gekocht)",83),
("grain","Makarna (pişmiş)","Pasta (cooked)","Nudeln (gekocht)",131),
("grain","Yulaf ezmesi (pişmiş)","Oatmeal (cooked)","Haferbrei (gekocht)",68),
("grain","Kinoa (pişmiş)","Quinoa (cooked)","Quinoa (gekocht)",120),
("grain","Müsli","Muesli","Müsli",340),
("grain","Kruvasan","Croissant","Croissant",406),
("grain","Lavaş","Lavash","Lavash-Brot",275),
("grain","Kepekli ekmek","Bran bread","Kleiebrot",224),
("grain","Mısır ekmeği","Cornbread","Maisbrot",296),
("grain","Buğday unu","Wheat flour","Weizenmehl",364),
("grain","Kuskus (pişmiş)","Couscous (cooked)","Couscous (gekocht)",112),
("grain","Galeta","Rusk","Zwieback",407),
("grain","Krep hamuru (sade)","Crepe batter (plain)","Crêpe-Teig (pur)",200),
# --- Süt ürünleri / Dairy / Milchprodukte ---
("dairy","Tam yağlı süt","Whole milk","Vollmilch",61),
("dairy","Yarım yağlı süt","Semi-skimmed milk","Halbfettmilch",46),
("dairy","Yoğurt","Yogurt","Joghurt",61),
("dairy","Süzme yoğurt","Greek yogurt","Griechischer Joghurt",97),
("dairy","Ayran","Ayran (yogurt drink)","Ayran (Joghurtgetränk)",35),
("dairy","Beyaz peynir","Feta cheese","Feta-Käse",264),
("dairy","Kaşar peyniri","Kashar cheese","Kaşar-Käse",350),
("dairy","Cheddar peyniri","Cheddar","Cheddar",403),
("dairy","Mozzarella","Mozzarella","Mozzarella",280),
("dairy","Krem peynir","Cream cheese","Frischkäse",342),
("dairy","Tereyağı","Butter","Butter",717),
("dairy","Krema","Cream","Sahne",340),
("dairy","Dondurma","Ice cream","Eiscreme",207),
("dairy","Labne","Labneh","Labneh",150),
("dairy","Kefir","Kefir","Kefir",41),
# --- Et / Protein / Meat & Protein / Fleisch & Proteine ---
("meat","Tavuk göğsü (ızgara)","Grilled chicken breast","Gegrillte Hähnchenbrust",165),
("meat","Tavuk but","Chicken thigh","Hähnchenschenkel",209),
("meat","Dana eti (yağsız)","Beef (lean)","Rindfleisch (mager)",217),
("meat","Kuzu eti","Lamb","Lammfleisch",294),
("meat","Kıyma (dana, yağsız)","Ground beef (lean)","Rinderhackfleisch (mager)",212),
("meat","Hindi eti","Turkey","Putenfleisch",135),
("meat","Sosis","Sausage","Wurst",301),
("meat","Sucuk","Sucuk (spicy sausage)","Sucuk (würzige Wurst)",380),
("meat","Pastırma","Pastırma (cured beef)","Pastırma (luftgetrocknetes Rindfleisch)",220),
("meat","Salam","Salami","Salami",336),
("meat","Jambon","Ham","Schinken",145),
("meat","Yumurta (haşlanmış)","Boiled egg","Gekochtes Ei",155),
("meat","Omlet","Omelette","Omelett",154),
("meat","Ton balığı (suda)","Tuna (in water)","Thunfisch (in Wasser)",116),
("meat","Somon","Salmon","Lachs",208),
("meat","Levrek","Sea bass","Wolfsbarsch",97),
("meat","Çipura","Sea bream","Dorade",121),
("meat","Karides","Shrimp","Garnelen",99),
("meat","Kalamar","Squid","Tintenfisch",92),
("meat","Midye","Mussels","Miesmuscheln",172),
("meat","Tofu","Tofu","Tofu",76),
("meat","Nohut (haşlanmış)","Chickpeas (cooked)","Kichererbsen (gekocht)",164),
("meat","Mercimek (haşlanmış)","Lentils (cooked)","Linsen (gekocht)",116),
("meat","Kuru fasulye (haşlanmış)","White beans (cooked)","Weiße Bohnen (gekocht)",127),
("meat","Barbunya (haşlanmış)","Borlotti beans (cooked)","Borlottibohnen (gekocht)",130),
# --- Türk yemekleri / Turkish dishes / Türkische Gerichte ---
("turkish","Karnıyarık","Karnıyarık (stuffed eggplant)","Karnıyarık (gefüllte Aubergine)",130),
("turkish","İmam bayıldı","İmam bayıldı","İmam Bayıldı",120),
("turkish","Mantı","Manti (Turkish dumplings)","Manti (türkische Teigtaschen)",210),
("turkish","Lahmacun","Lahmacun","Lahmacun",235),
("turkish","Pide (kıymalı)","Pide with minced meat","Pide mit Hackfleisch",260),
("turkish","Döner (tavuk)","Chicken döner","Hähnchen-Döner",220),
("turkish","Döner (et)","Beef döner","Rind-Döner",250),
("turkish","İskender","İskender kebab","İskender-Kebab",240),
("turkish","Adana kebap","Adana kebab","Adana-Kebab",250),
("turkish","Şiş kebap","Shish kebab","Schaschlik",210),
("turkish","Köfte (ızgara)","Grilled meatballs","Gegrillte Köfte",220),
("turkish","Menemen","Menemen (Turkish scrambled eggs)","Menemen (türkisches Rührei)",130),
("turkish","Mercimek çorbası","Lentil soup","Linsensuppe",90),
("turkish","Yaprak sarma (zeytinyağlı)","Stuffed grape leaves (olive oil)","Gefüllte Weinblätter (mit Olivenöl)",180),
("turkish","Etli dolma","Stuffed vegetables with meat","Gefülltes Gemüse mit Fleisch",140),
("turkish","Pilav (tereyağlı)","Buttered rice pilaf","Reispilaw mit Butter",170),
("turkish","Bulgur pilavı","Bulgur pilaf","Bulgurpilaw",150),
("turkish","Kuru fasulye yemeği","Turkish white bean stew","Türkischer weißer Bohneneintopf",130),
("turkish","Nohut yemeği","Turkish chickpea stew","Türkischer Kichererbsen-Eintopf",140),
("turkish","Türlü","Turkish mixed vegetable stew","Türkischer Gemüseeintopf",90),
("turkish","Mücver","Zucchini fritters","Zucchini-Puffer",180),
("turkish","Çiğ köfte (vegan)","Çiğ köfte (vegan)","Çiğ Köfte (vegan)",160),
("turkish","Ezogelin çorba","Ezogelin soup","Ezogelin-Suppe",85),
("turkish","Tarhana çorbası","Tarhana soup","Tarhana-Suppe",80),
("turkish","İşkembe çorbası","Tripe soup","Kuttelsuppe",110),
("turkish","Kelle paça","Head and trotter soup","Kopf-Fuß-Suppe",150),
("turkish","Hünkarbeğendi","Hünkarbeğendi (eggplant puree with meat)","Hünkarbeğendi (Auberginenpüree mit Fleisch)",180),
("turkish","Testi kebabı","Clay pot kebab","Tontopf-Kebab",220),
("turkish","Yayla çorbası","Yayla soup (yogurt soup)","Yayla-Suppe (Joghurtsuppe)",75),
("turkish","Baklava","Baklava","Baklava",430),
("turkish","Kısır","Kısır (bulgur salad)","Kısır (Bulgursalat)",180),
# --- Uluslararası yemekler / International dishes / Internationale Gerichte ---
("intl","Pizza (margarita)","Pizza margherita","Pizza Margherita",266),
("intl","Hamburger","Hamburger","Hamburger",295),
("intl","Cheeseburger","Cheeseburger","Cheeseburger",303),
("intl","Sezar salata (tavuklu)","Chicken Caesar salad","Hühner-Caesar-Salat",190),
("intl","Sushi (somonlu)","Salmon sushi","Lachs-Sushi",150),
("intl","Pad thai","Pad Thai","Pad Thai",180),
("intl","Schnitzel","Schnitzel","Schnitzel",280),
("intl","Lazanya","Lasagna","Lasagne",135),
("intl","Risotto","Risotto","Risotto",170),
("intl","Paella","Paella","Paella",160),
("intl","Fish and chips","Fish and chips","Fish and Chips",230),
("intl","Ratatouille","Ratatouille","Ratatouille",65),
("intl","Güveç (goulash)","Goulash","Gulasch",150),
("intl","Falafel","Falafel","Falafel",333),
("intl","Humus","Hummus","Hummus",166),
("intl","Taco (etli)","Beef tacos","Rind-Tacos",226),
("intl","Burrito","Burrito","Burrito",206),
("intl","Köri (tavuklu)","Chicken curry","Hähnchen-Curry",165),
("intl","Ramen","Ramen","Ramen",150),
("intl","Pho","Pho","Pho",90),
("intl","Dim sum","Dim sum","Dim Sum",200),
("intl","Kimçi","Kimchi","Kimchi",23),
("intl","Bibimbap","Bibimbap","Bibimbap",150),
("intl","Musakka","Moussaka","Moussaka",185),
("intl","Cacık / Tzatziki","Tzatziki","Tzatziki",95),
("intl","Gazpacho","Gazpacho","Gazpacho",45),
("intl","Bruschetta","Bruschetta","Bruschetta",150),
("intl","Kiş (quiche)","Quiche","Quiche",300),
("intl","Waffle","Waffle","Waffel",291),
("intl","Pankek","Pancake","Pfannkuchen",227),
# --- Fast food / Fast Food / Fast Food ---
("fastfood","Patates kızartması","French fries","Pommes frites",312),
("fastfood","Tavuk nugget","Chicken nuggets","Chicken Nuggets",296),
("fastfood","Soğan halkası","Onion rings","Zwiebelringe",411),
("fastfood","Sosisli sandviç","Hot dog","Hot Dog",290),
("fastfood","Kızarmış tavuk","Fried chicken","Frittiertes Hähnchen",260),
("fastfood","Wrap (tavuklu)","Chicken wrap","Hähnchen-Wrap",190),
("fastfood","Club sandviç","Club sandwich","Club Sandwich",250),
("fastfood","Nachos (peynirli)","Nachos with cheese","Nachos mit Käse",346),
("fastfood","Kızarmış mozzarella çubuğu","Fried mozzarella sticks","Frittierte Mozzarella-Sticks",297),
("fastfood","Milkshake","Milkshake","Milchshake",112),
("fastfood","Donut","Donut","Donut",452),
("fastfood","Pizza dilimi (pepperoni)","Pepperoni pizza slice","Pepperoni-Pizza-Stück",298),
("fastfood","Tavuklu burger","Chicken burger","Chicken Burger",285),
("fastfood","Tatlı patates kızartması","Sweet potato fries","Süßkartoffel-Pommes",229),
("fastfood","Corn dog","Corn dog","Corn Dog",260),
# --- Tatlılar / Atıştırmalık / Desserts & Snacks / Süßigkeiten & Snacks ---
("dessert","Çikolata (sütlü)","Milk chocolate","Vollmilchschokolade",535),
("dessert","Bitter çikolata","Dark chocolate","Zartbitterschokolade",546),
("dessert","Kek (sade)","Plain cake","Kuchen (pur)",371),
("dessert","Cheesecake","Cheesecake","Cheesecake",321),
("dessert","Tiramisu","Tiramisu","Tiramisu",283),
("dessert","Muffin","Muffin","Muffin",377),
("dessert","Kurabiye","Cookies","Kekse",502),
("dessert","Bisküvi","Biscuits","Kekse (Biscuits)",450),
("dessert","Sütlaç","Rice pudding","Milchreis",130),
("dessert","Kazandibi","Kazandibi (caramelized milk pudding)","Kazandibi (karamellisierter Milchpudding)",150),
("dessert","Güllaç","Güllaç","Güllaç",140),
("dessert","Lokum","Turkish delight","Türkischer Honig (Lokum)",325),
("dessert","Helva (un)","Halva (flour)","Halva (Mehl)",470),
("dessert","Cips (patates)","Potato chips","Kartoffelchips",536),
("dessert","Patlamış mısır (tuzlu)","Popcorn (salted)","Popcorn (gesalzen)",387),
("dessert","Kraker","Crackers","Cracker",421),
("dessert","Gofret","Wafer bar","Waffelriegel",495),
("dessert","Marshmallow","Marshmallow","Marshmallow",318),
("dessert","Jöle şeker","Gummy candy","Gummibonbons",343),
("dessert","Trileçe","Trileçe (three-milk cake)","Trileçe (Drei-Milch-Kuchen)",250),
("dessert","Profiterol","Profiterole","Profiterole",300),
("dessert","Puding (çikolatalı)","Chocolate pudding","Schokoladenpudding",150),
("dessert","Granola bar","Granola bar","Müsliriegel",471),
("dessert","Kuru meyve karışımı","Dried fruit mix","Trockenfrüchte-Mix",320),
("dessert","Reçel","Jam","Marmelade",278),
# --- İçecekler / Drinks / Getränke ---
("drink","Su","Water","Wasser",0),
("drink","Kola","Cola","Cola",42),
("drink","Portakal suyu","Orange juice","Orangensaft",45),
("drink","Elma suyu","Apple juice","Apfelsaft",46),
("drink","Limonata","Lemonade","Limonade",40),
("drink","Çay (şekersiz)","Tea (unsweetened)","Tee (ungesüßt)",1),
("drink","Türk kahvesi (şekersiz)","Turkish coffee (unsweetened)","Türkischer Kaffee (ungesüßt)",2),
("drink","Espresso","Espresso","Espresso",9),
("drink","Latte","Latte","Latte Macchiato",60),
("drink","Cappuccino","Cappuccino","Cappuccino",45),
("drink","Sıcak çikolata","Hot chocolate","Heiße Schokolade",78),
("drink","Enerji içeceği","Energy drink","Energy-Drink",45),
("drink","Spor içeceği","Sports drink","Sportgetränk",25),
("drink","Bira","Beer","Bier",43),
("drink","Kırmızı şarap","Red wine","Rotwein",85),
("drink","Beyaz şarap","White wine","Weißwein",82),
("drink","Votka","Vodka","Wodka",231),
("drink","Meyveli smoothie","Fruit smoothie","Frucht-Smoothie",60),
("drink","Protein shake","Protein shake","Proteinshake",80),
("drink","Soda (sade)","Soda water","Sodawasser",0),
("drink","Şalgam suyu","Turnip juice","Rübensaft",15),
("drink","Boza","Boza (fermented millet drink)","Boza (fermentiertes Hirsegetränk)",90),
("drink","Nane limon","Mint lemonade","Minz-Limonade",35),
("drink","Kayısı nektarı","Apricot nectar","Aprikosennektar",55),
("drink","Hindistan cevizi suyu","Coconut water","Kokoswasser",19),
# --- Çorbalar / Soups / Suppen ---
("soup","Domates çorbası","Tomato soup","Tomatensuppe",35),
("soup","Tavuk suyu çorba","Chicken soup","Hühnersuppe",40),
("soup","Mantar çorbası","Mushroom soup","Pilzsuppe",45),
("soup","Brokoli çorbası","Broccoli soup","Brokkolisuppe",40),
("soup","Karnabahar çorbası","Cauliflower soup","Blumenkohlsuppe",38),
("soup","Balkabağı çorbası","Pumpkin soup","Kürbissuppe",42),
("soup","Mısır çorbası","Corn soup","Maissuppe",55),
("soup","Sebze çorbası","Vegetable soup","Gemüsesuppe",30),
("soup","Şehriye çorbası","Noodle soup","Nudelsuppe",45),
("soup","Kremalı mantar çorbası","Cream of mushroom soup","Cremige Pilzsuppe",65),
("soup","Balık çorbası","Fish soup","Fischsuppe",55),
("soup","Pancar çorbası","Beet soup","Rote-Bete-Suppe",33),
# --- Kuruyemiş / Nuts / Nüsse ---
("nuts","Fındık","Hazelnut","Haselnuss",628),
("nuts","Badem","Almond","Mandel",579),
("nuts","Ceviz","Walnut","Walnuss",654),
("nuts","Antep fıstığı","Pistachio","Pistazie",560),
("nuts","Kaju","Cashew","Cashewkerne",553),
("nuts","Yer fıstığı","Peanut","Erdnuss",567),
("nuts","Kabak çekirdeği","Pumpkin seeds","Kürbiskerne",559),
("nuts","Ay çekirdeği","Sunflower seeds","Sonnenblumenkerne",584),
("nuts","Makademya","Macadamia","Macadamianuss",718),
("nuts","Brezilya fıstığı","Brazil nut","Paranuss",656),
# --- Baklagiller / Legumes / Hülsenfrüchte ---
("legume","Bakla (haşlanmış)","Fava beans (cooked)","Dicke Bohnen (gekocht)",88),
("legume","Börülce (haşlanmış)","Black-eyed peas (cooked)","Augenbohnen (gekocht)",116),
("legume","Soya fasulyesi (haşlanmış)","Soybeans (cooked)","Sojabohnen (gekocht)",173),
("legume","Yeşil mercimek (haşlanmış)","Green lentils (cooked)","Grüne Linsen (gekocht)",116),
("legume","Kırmızı mercimek (haşlanmış)","Red lentils (cooked)","Rote Linsen (gekocht)",116),
("legume","Kidney fasulye (haşlanmış)","Kidney beans (cooked)","Kidneybohnen (gekocht)",127),
("legume","Edamame","Edamame","Edamame",121),
("legume","Lima fasulyesi (haşlanmış)","Lima beans (cooked)","Limabohnen (gekocht)",115),
("legume","Beyaz fasulye pilaki","White bean pilaki","Weiße-Bohnen-Pilaki",110),
("legume","Mercimek köftesi (vegan)","Lentil balls (vegan)","Linsenbällchen (vegan)",180),
# --- Deniz ürünleri / Seafood / Meeresfrüchte ---
("seafood","Hamsi (kızartma)","Fried anchovy","Frittierte Sardelle",210),
("seafood","Palamut (ızgara)","Grilled bonito","Gegrillter Bonito",170),
("seafood","Alabalık","Trout","Forelle",148),
("seafood","Ahtapot","Octopus","Oktopus",82),
("seafood","İstiridye","Oyster","Auster",68),
("seafood","Yengeç","Crab","Krabbe",97),
("seafood","Istakoz","Lobster","Hummer",89),
("seafood","Uskumru","Mackerel","Makrele",205),
("seafood","Morina balığı","Cod","Kabeljau",82),
("seafood","Ton balığı (ızgara)","Grilled tuna","Gegrillter Thunfisch",144),
# --- Kahvaltılık / Breakfast / Frühstück ---
("breakfast","Sahanda yumurta","Fried egg","Spiegelei",196),
("breakfast","Çılbır (poşe yumurta, yoğurtlu)","Poached egg with yogurt","Pochiertes Ei mit Joghurt",190),
("breakfast","Sucuklu yumurta","Eggs with sucuk","Eier mit Sucuk",260),
("breakfast","Kaymak","Clotted cream","Kaymak (Rahmcreme)",380),
("breakfast","Bal","Honey","Honig",304),
("breakfast","Tahin","Tahini","Tahin",595),
("breakfast","Pekmez","Grape molasses","Traubenmelasse",292),
("breakfast","Zeytin (siyah)","Black olives","Schwarze Oliven",115),
("breakfast","Zeytin (yeşil)","Green olives","Grüne Oliven",145),
("breakfast","Peynir tabağı (karışık)","Mixed cheese plate","Gemischter Käseteller",300),
("breakfast","Fıstık ezmesi","Peanut butter","Erdnussbutter",588),
("breakfast","Fındık kreması (Nutella tarzı)","Hazelnut spread","Nuss-Nougat-Creme",539),
("breakfast","Granola","Granola","Granola",471),
("breakfast","Krep (tuzlu, peynirli)","Savory crepe with cheese","Herzhafter Crêpe mit Käse",220),
("breakfast","Kahvaltı tabağı (karışık)","Mixed breakfast plate","Gemischter Frühstücksteller",250),
]

CATEGORY_DEFAULTS = {
    # cat: (default_g, tr_unit, en_unit, de_unit, is_liquid)
    "fruit":     (150, "orta boy adet", "medium piece", "mittelgroßes Stück", False),
    "veg":       (100, "porsiyon", "serving", "Portion", False),
    "grain":     (30,  "dilim", "slice", "Scheibe", False),
    "dairy":     (200, "kase", "bowl", "Schale", False),
    "meat":      (150, "porsiyon", "serving", "Portion", False),
    "turkish":   (300, "porsiyon", "serving", "Portion", False),
    "intl":      (300, "porsiyon", "serving", "Portion", False),
    "fastfood":  (250, "porsiyon", "serving", "Portion", False),
    "dessert":   (100, "dilim", "Stück", "Stück", False),
    "drink":     (200, "bardak", "glass", "Glas", True),
    "soup":      (250, "kase", "bowl", "Schale", True),
    "nuts":      (30,  "avuç", "handful", "Handvoll", False),
    "legume":    (200, "porsiyon", "serving", "Portion", False),
    "seafood":   (150, "porsiyon", "serving", "Portion", False),
    "breakfast": (100, "porsiyon", "serving", "Portion", False),
}

GRAM_STEPS = [25,50,75,100,125,150,175,200,225,250,275,300,350,400,450,500]

rows = []
for cat, tr, en, de, kcal100 in BASE_FOODS:
    default_g, tr_unit, en_unit, de_unit, is_liquid = CATEGORY_DEFAULTS[cat]
    unit_label = "ml" if is_liquid else "g"

    # default serving variant (natural language)
    serv_kcal = round(kcal100 * default_g / 100)
    rows.append({
        "t": f"{tr} — 1 {tr_unit} (~{default_g} {unit_label})",
        "e": f"{en} — 1 {en_unit} (~{default_g} {unit_label})",
        "d": f"{de} — 1 {de_unit} (~{default_g} {unit_label})",
        "k": serv_kcal,
    })

    # gram/ml step variants
    for g in GRAM_STEPS:
        k = round(kcal100 * g / 100)
        rows.append({
            "t": f"{tr} — {g} {unit_label}",
            "e": f"{en} — {g} {unit_label}",
            "d": f"{de} — {g} {unit_label}",
            "k": k,
        })

print("base foods:", len(BASE_FOODS))
print("total rows:", len(rows))

with open("/sessions/stoic-kind-keller/mnt/outputs/foods.js", "w", encoding="utf-8") as f:
    f.write("// Otomatik üretilmiş çok dilli (TR/EN/DE) yiyecek-içecek veritabanı\n")
    f.write("// Kalori değerleri 100g/100ml baz alınarak hesaplanmış yaklaşık değerlerdir.\n")
    f.write("const FOOD_DB = ")
    f.write(json.dumps(rows, ensure_ascii=False, separators=(',', ':')))
    f.write(";\n")

print("wrote foods.js")
